version: '3'
services:
  ngrok:
    image: wernight/ngrok
    environment:
      - NGROK_PORT=8080
    ports:
      - "4040:4040"
    links:
      - web:http
  web:
    network_mode: host
    build: .
    ports:
      - "8080:4040"
    restart: unless-stopped
    # depends_on:
    #   - ngrok


      
